from pathlib import Path
import shutil,json,hashlib
out=Path('.build/brahms-remaining-2026-10-03/upper-review');core=out/'Core';shutil.copytree('Partsmith/Core',core,dirs_exist_ok=True)
s=(core/'Detection/NativeScorePageAnalyzer.swift').read_text().replace('enum NativeScorePageAnalyzer','enum ProbeNativeScorePageAnalyzer')
s=s.replace('        let original = ink','        let original = ink\n        Trace.saveMask(original,width:width,height:height,phase:retainMusicalEvidence ? "original-musical":"original-structural")')
s=s.replace('        var preservedMusicalConnection = false','        Trace.saveMask(ink,width:width,height:height,phase:retainMusicalEvidence ? "staff-erased-musical":"staff-erased-structural")\n        Trace.emit("staff-geometry",["musical":retainMusicalEvidence,"lines":lines,"spaces":spaces,"lineStarts":lineStarts])\n        var preservedMusicalConnection = false')
s=s.replace('                        // Local page curl can move all five','                        if index == 0 { Trace.emit("connector",["musical":retainMusicalEvidence,"left":left,"right":x,"clear":[clearLeft,clearRight],"physicalStrokes":physicalStrokes.map{[$0.left,$0.right]},"cores":throughBothCores,"start":start,"end":end,"space":space,"localShift":localShift]) }\n                        // Local page curl can move all five')
s=s.replace('if let bestShift, Double(abs(bestShift)) + 2 < staffSpace { return Double(bestShift) }','if let bestShift, Double(abs(bestShift)) + 2 < staffSpace { if index == 0 { Trace.emit("local-shift",["staff":staffIndex,"left":left,"right":x,"shift":bestShift]) };return Double(bestShift) }')
s=s.replace('guard let upper = localCoreShift(index), let lower = localCoreShift(index + 1) else { continue }','guard let upper = localCoreShift(index), let lower = localCoreShift(index + 1) else { if index == 0 {Trace.emit("rejected-local-trace",["left":left,"right":x])};continue }')
s=s.replace('guard connectorProof(index, upperCoreShift),\n                                  connectorProof(index + 1, lowerCoreShift) else { continue }','guard connectorProof(index, upperCoreShift),\n                                  connectorProof(index + 1, lowerCoreShift) else { if index == 0 {Trace.emit("rejected-core-junction-proof",["left":left,"right":x,"upperShift":upperCoreShift,"lowerShift":lowerCoreShift,"upperProof":connectorProof(index,upperCoreShift),"lowerProof":connectorProof(index+1,lowerCoreShift)])};continue }')
s=s.replace('                        if ownsTerminalHead {','                        if index == 0 {Trace.emit("terminal-test",["left":left,"right":x,"ownsTerminalHead":ownsTerminalHead,"musical":retainMusicalEvidence])}\n                        if ownsTerminalHead {')
s=s.replace('                        for y in localStart..<localEnd {','                        if index == 0 {Trace.emit("cut",["left":clearLeft,"right":clearRight,"top":localStart,"bottom":localEnd,"musical":retainMusicalEvidence])}\n                        for y in localStart..<localEnd {')
s=s.replace('        struct Run { var left: Int; var right: Int; var y: Int }','        Trace.saveMask(ink,width:width,height:height,phase:retainMusicalEvidence ? "separated-musical":"separated-structural")\n        struct Run { var left: Int; var right: Int; var y: Int }')
(out/'ProbeNativeScorePageAnalyzer.swift').write_text(s)
files={str(p.relative_to(core)):hashlib.sha256(p.read_bytes()).hexdigest() for p in core.rglob('*.swift')}
(out/'source-hashes.json').write_text(json.dumps(files,indent=2)+'\n')
