from pathlib import Path
import json,hashlib
W=Path('.build/brahms-monotone-independent-2026-10-03');R=W/'ending-review';read=lambda p:json.loads(Path(p).read_text());sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();rows=read(R/'bindings-before-review.json');manifest=read('.build/brahms-source-span-full-replay-2026-10-03/inputs.json');beforePath=Path('.build/brahms-envelope-compatibility-full-2026-10-03/candidate.json');afterPath=Path('.build/brahms-monotone-compatibility-full-2026-10-03/candidate.json');old=read(beforePath);new=read(afterPath)
notes={
'p25-s3-violin1':'All target high ledger notes, upper slur, lower slurs, hairpins and forte marks remain inside. Small lower expansion adds a strip of the following Violin II staff; no target recovery observed.',
'p26-s2-violin1':'Low tied notes, hairpin, p/pp/dim. and final staccato dots remain inside. Lower expansion enters the following Violin II top staff/clef fragment; no target recovery observed.',
'p26-s4-viola':'Target lower slurs, hairpins and forte remain inside. Lower expansion includes more of the following Cello top line and slur/note fragments.',
'p28-s1-violin2':'Target lower notes, articulations, hairpin and forte remain inside. Upper neighboring Violin I fragments remain from the unchanged top edge; the lower expansion adds Viola top-line/notation fragments.',
'p31-s1-viola':'Target low notes, staccato dots, slurs, piano and rightmost hairpin remain inside. Tiny lower expansion adds Cello top-line/notation fragments.',
'p31-s2-viola':'Target lower slurs, dots, pp and hairpins remain inside. Lower expansion includes additional Cello upper line/beam/slur fragments.',
'p32-s3-viola':'Target repeat sign, beams, accidentals, triplet numerals, dots, lower slurs and hairpins remain inside. Lower expansion enters the Cello upper line and notation fragments.',
'p32-s4-violin1':'Target high ledger notes and slurs, both printed ending brackets/numerals, piano and trailing key change remain inside. Lower expansion adds more Violin II upper-staff fragments; previous Cello fragments remain at unchanged top edge.',
'p35-s2-violin2':'Target lower ledger-note chords, stems, accents and slurs remain inside. Lower expansion adds conspicuous Viola noteheads/upper-line fragments, with no target recovery observed. This is system 2 and does not resolve the separate frozen page-35 system-1 guard failure.',
'p37-s1-violin1':'High target ledger notes, accidentals, slurs, forte and final hairpin remain inside. Tiny lower expansion adds Violin II upper-line fragments.',
'p37-s4-violin2':'Target low ledger notes, dots, long tie/slur and complete cresc. poco a poco text remain inside. Tiny lower expansion adds Viola upper-line fragments.',
'p38-s1-violin1':'Target high dotted notes, ledger lines, triplet numeral, final slur and forte remain inside. Lower expansion includes additional Violin II top-line/note fragments.',
'p39-s4-viola':'Target chords, slurs, hairpin, forte and final fermata remain inside. Tiny lower expansion adds Cello upper-line fragments; neighboring arco was already within the lower context.'}
for row in rows:
 assert sha(row['source'])==manifest[row['source']]==row['sourceSHA256'];assert sha(row['annotatedPanel'])==row['annotatedSHA256'];i=row['page']-1;pg0,pg1=old['pages'][i],new['pages'][i];assert {k:v for k,v in pg0.items()if k!='inkComponents'}=={k:v for k,v in pg1.items()if k!='inkComponents'}
 a=next(b for b in old['plan']['pages'][i]['assignments']if b['id']==row['band']);b=next(b for b in new['plan']['pages'][i]['assignments']if b['id']==row['band']);assert a['candidateIDs']==b['candidateIDs']
 Y=lambda z:[z['topFraction']*pg0['pageHeight'],z['bottomFraction']*pg0['pageHeight']];assert Y(a)==row['oldY'] and Y(b)==row['newY'];assert row['oldY'][0]==row['newY'][0] and row['newY'][1]>=row['oldY'][1]
 foreign=lambda z:[s['id']for s in pg0['staves']if s['id']not in z['candidateIDs']and z['topFraction']<=min(s['staffLineFractions'])and z['bottomFraction']>=max(s['staffLineFractions'])]
 row.update({'candidateIDs':b['candidateIDs'],'beforeWholeForeignIDs':foreign(a),'afterWholeForeignIDs':foreign(b),'newWholeForeignIDs':sorted(set(foreign(b))-set(foreign(a))),'sourceInspectedBeforeOverlays':True,'annotatedPanelIndividuallyInspected':True,'newTargetOmissionObserved':False,'targetRecoveryObserved':False,'observation':notes[row['band']]});assert not row['newWholeForeignIDs']
review={'reviewer':'ending_delivery','scope':'All 13 expansion-only corrected-Brahms source rows on physical pages 25–39 delegated by crop_algorithm_audit; comparison is prior private e32 candidate versus private monotone95 candidate, not exported pages.','method':'Viewed all 13 unannotated full-width original source areas first in four contact images, then each of the 13 annotated full-width panels individually. Exact original raster hashes, source/staff fields, candidateIDs and old/new crop bounds independently verified.','beforeInventory':str(beforePath),'beforeSHA256':sha(beforePath),'afterInventory':str(afterPath),'afterSHA256':sha(afterPath),'sourceManifestSHA256':sha('.build/brahms-source-span-full-replay-2026-10-03/inputs.json'),'rows':rows,'verdict':'No new target omission observed in these 13 rows; no new complete foreign-staff relation. Every expansion adds or retains partial neighboring notation. No target-recovery justification was observed for the expanded strips.','limits':'This is a bounded source-area preservation review, not full-score cleanliness, existing-omission certification, PDF layout or release approval. Frozen source guards remain unchanged and their existing failures remain failures.'}
(R/'review.json').write_text(json.dumps(review,indent=2)+'\n');(R/'hashes.json').write_text(json.dumps({p.name:sha(p)for p in sorted(R.iterdir())if p.is_file()and p.name!='hashes.json'},indent=2)+'\n');print('review',sha(R/'review.json'),'hashes',sha(R/'hashes.json'))
