from pathlib import Path
import hashlib,json
r=Path('Tests/quality_control/schumann-heading-block-output');root=Path('.build/schumann-heading-output-2026-10-03');native=Path('.build/heading-blocks-2026-10-03/native-worker-final');snap=Path('.build/heading-blocks-2026-10-03/candidate-final');out=root/'parts'
load=lambda p:json.loads(p.read_text());sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
m=load(out/'manifest.json');project=out/m['project'];source=Path(m['source']);assert sha(project/'source.pdf')==sha(source)==m['sourceSHA256']
old=Path('output/pdf/auto-qc-2026-09-21/schumann-quintet-06822-native-auto');oldm=load(old/'manifest.json');before=load(old/oldm['project']/'project.json')['project'];after=load(project/'project.json')['project'];assert before['projectSettings']==after['projectSettings'];assert len(after['parts'])==5 and len(after['bands'])==825
paths=[source,Path('Tests/quality_control/profiles/medium-skewed-03-schumann-piano-quintet-op44-imslp-06822.json'),snap/'source-hashes.json',native/'native_worker.swift',native/'native_worker',native/'config.json',native/'build.sh',native/'schumann-summary.json',native/'schumann-inventory.json',native/'schumann-plan.json',root/'export_score_plan.swift',root/'exporter',root/'build-exporter.sh',root/'export.sh',root/'compare.py',out/'manifest.json',out/'plan.json',project/'source.pdf',project/'project.json']+[out/p['file'] for p in m['parts']]
report=[r/'frozen-baseline-inputs.json',r/'p26-independent-source-guard.json',r/'p26-source-speck-classification.json',r/'comparison.json',r/'source-guard-validation.json']
j={'status':'draft — source and output review; not whole-score recall certification','sourceSHA256':m['sourceSHA256'],'coreSnapshot':str(snap),'coreSources':load(snap/'source-hashes.json'),'files':[{'path':str(p),'sha256':sha(p)} for p in paths+report],'sourceEmbeddedProjectVerified':True,'originalProjectSettingsPreserved':True,'sourcePageCount':56,'musicSystemsPerPart':165,'parts':5,'pages':sum(p['outputPages'] for p in m['parts']),'bands':825,'sourceCopies':sum(len(b['sourceMarkings']) for p in m['parts'] for b in p['placements'])}
(r/'provenance.json').write_text(json.dumps(j,indent=2)+'\n');print(json.dumps({k:v for k,v in j.items() if k not in ['files','coreSources']},indent=2))
