from pathlib import Path
import hashlib,json,shutil
R=Path('.build/monotone-corpus-independent-2026-10-03');W=Path('.build/monotone-line-corpus-2026-10-03');B=Path('.build/envelope-corpus-independent-2026-10-03');sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();read=lambda p:json.loads(Path(p).read_text())
assert sha(B/'baseline-binding.json')=='425a4fd3fd7dcba6009c00e1a58bc2a0f104a7e6952ffbc96109d6b733af4e21'
base=read(B/'baseline-binding.json');inputs=read(W/'inputs.json');by={x['id']:x for x in base['rows']};assert len(inputs)==36 and sum(x['pages']for x in inputs)==1477
bind=read(W/'build-binding.json');assert bind['sourceHashes']['Detection/NativeScorePageAnalyzer.swift']=='95a958a328a729cf4c8d64421a96c1dd2533b3b38a68606fb1ead3c21cf780e0';assert sha(bind['binary'])==bind['binarySHA256']
for rel,h in bind['sourceHashes'].items():assert sha(Path(bind['snapshot'])/rel)==h
for inp in inputs:
 old=by[inp['id']]
 for key in ['source','sourceSHA256','profile','profileSHA256','pages','baseline','baselineSHA256']:assert inp[key]==old[key]
 for field,hashField in [('source','sourceSHA256'),('profile','profileSHA256'),('baseline','baselineSHA256')]:assert sha(inp[field])==inp[hashField]
 assert sha(old['replannedBaseline'])==old['replannedBaselineSHA256']
base['candidateBuildBindingSHA256']=sha(W/'build-binding.json');base['priorVerifiedBaselineBindingSHA256']=sha(B/'baseline-binding.json');base['originalPDFGeometryReuse']='Every source PDF is byte-identical to the independently opened original; original recorded PDF page geometry reused without rerendering.'
(R/'baseline-binding.json').write_text(json.dumps(base,indent=2)+'\n')
for n in ['compare.py','finish-comparison.py']:
 s=(B/n).read_text().replace(str(B),str(R)).replace('.build/envelope-compatibility-corpus-2026-10-03',str(W));s=s.replace('Incomplete and stopped after concrete new-neighbor regressions; no blanket source-preservation pass.','Pending source review; geometry checks do not establish preservation.').replace('Rejected real cleanliness gate. Aggregated neighbor reduction does not cancel the three new per-band foreign-staff relations.','Pending independent real-source review and parent decision; no production approval from this comparator.');(R/n).write_text(s)
protocol={'scope':'Read-only independent comparison of all 36 unchanged PDFs / 1477 pages against original production9f8 raw analyses replanned with current772; no native workers or baseline detection.','sourceExpectations':'Reuse exact frozen prior source/profile/PDF-geometry bindings after hashing all originals again. Same source-owned expectations; unresolved pages and zero-band profiles do not count as successful extraction.','checks':'All source hashes, executable and Core, page geometry and staff identity/order, every assignment and order, warnings/unresolved metadata, all crop edges, per-band foreign-staff ID sets, component changes and unresolved coverage.','visualReviewReuse':'A prior visual source crop finding may only be reused if source byte hash, physical page, intended assignment/candidate IDs, and both crop rectangles match exactly. Changed geometry needs new source review.','newSourceGates':'New foreign-staff relation is a failure even if aggregate improves. Inward changes are queued for original-source inspection; no blanket source preservation claim from bounds alone.','candidateAnalyzerSHA256':bind['sourceHashes']['Detection/NativeScorePageAnalyzer.swift'],'priorBaselineBindingSHA256':sha(B/'baseline-binding.json')}
(R/'independent-protocol-before-comparison.json').write_text(json.dumps(protocol,indent=2)+'\n');print(json.dumps({'protocol':sha(R/'independent-protocol-before-comparison.json'),'baselineBinding':sha(R/'baseline-binding.json'),'sources':36,'pages':1477},indent=2))
