from pathlib import Path
import json,hashlib,os,shutil,tempfile,zipfile
from datetime import datetime,timezone
r=Path(__file__).resolve().parents[3];out=Path(__file__).resolve().parent;w=r/'.build/matcher-connection-release-2026-10-03';public=r/'artifacts/macos/Partsmith-extraction-preview-macos.zip';package=w/public.name
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
audit=json.loads((out/'independent-package-audit.json').read_text());assert audit['result']=='pass';assert sha(package)==audit['package']['sha256']=='7b3e5344a340be05973b465453c7c89b35f4a04d1f76b6456ed26f8495fc57ff'
inputs=json.loads((w/'source-hashes.json').read_text());oldinputs=json.loads((r/'Tests/quality_control/shared-direction-default-release-2026-10-03/source-hashes.json').read_text());assert set(inputs)==set(oldinputs)
for n,h in inputs.items():assert sha(r/n)==sha(w/n)==h,n
changed=[n for n in inputs if inputs[n]!=oldinputs[n]];assert changed==['Partsmith/Core/Detection/ScoreSystemTemplateMatcher.swift'];assert inputs[changed[0]]=='5d503a093d645373058827f3ed9865de1c9b8bd1f77144c178c9232d154c4f42'
assert inputs['Partsmith/Core/Detection/NativeScorePageAnalyzer.swift']=='9f8d7ef80a27569ca3f5711388ad5876326a2931d60ecd77b2703d0aba235f01'
trial=r/'Tests/quality_control/hear-my-prayer-template-matcher-2026-10-03';comparison=json.loads((trial/'candidate/source-comparison.json').read_text());assert comparison['matched']==26 and not comparison['wrong'] and comparison['unmatched']==6
for n in ['baseline','candidate']:
 assessment=json.loads((trial/f'{n}-challenge-results-assessment.json').read_text());assert assessment['total']==assessment['passed']==32 and assessment['failed']==0
assert json.loads((trial/'challenge-comparison.json').read_text())==[]
previous=sha(public);assert previous=='e4d177f85139c748fb308faafea3a4c719645de416e18b6f8c0d3fb3c646586e';backup=w/f'previous-public-{previous}.zip';shutil.copy2(public,backup);assert sha(backup)==previous
with tempfile.NamedTemporaryFile(dir=public.parent,prefix='.matcher-connection-',suffix='.zip',delete=False) as f:
 replacement=Path(f.name);f.write(package.read_bytes());f.flush();os.fsync(f.fileno())
assert sha(replacement)==sha(package) and sha(public)==previous;os.chmod(replacement,0o644);os.replace(replacement,public);assert sha(public)==audit['package']['sha256']
shutil.copy2(w/'source-hashes.json',out/'source-hashes.json')
with zipfile.ZipFile(out/'build-log.zip','w',zipfile.ZIP_DEFLATED) as z:z.write(w/'build.log','build.log')
record={'publishedAtUTC':datetime.now(timezone.utc).isoformat(),'change':'Use actual continuous source-ink evidence for Find Similar Systems even when brackets shift estimated staff starts; includes existing direct Preview crop editing.','artifact':str(public.relative_to(r)),'artifactSHA256':sha(public),'artifactBytes':public.stat().st_size,'executableSHA256':audit['executable']['sha256'],'previousArtifactSHA256':previous,'previousArtifactBackup':str(backup.relative_to(r)),'changedApplicationFiles':changed,'architectures':['arm64','x86_64'],'minimumMacOS':'14.0','signing':'Strictly verified ad hoc, not notarized.','nativeCropDetectorUnchanged':True,'privateOwnershipCandidateIncluded':False,'validation':{'buildInputs':45,'swiftInputs':35,'unchangedIndependentChallengeCasesPassed':32,'challengeSemanticsExactBaseline':True,'sourcePages':10,'sourceSystems':34,'reviewedSeeds':2,'correctAdditionalMatches':26,'wrongMatches':0,'systemsRemainingManual':6,'countsNotInferred':True,'independentPackageAuditSHA256':sha(out/'independent-package-audit.json'),'matcherExperimentManifestSHA256':sha(trial/'manifest.json')},'limits':['Matching still proposes reviewed roster examples rather than identifying instruments or counting rests.','Six systems in the scanned example still require manual assignment.','A printed connection is not a musical completeness guarantee; users still review proposed rosters.','Separate crop ownership experiments remain private.'],'runningAppOrUserDocumentModified':False,'publication':'Verified same-directory atomic ZIP replacement only.'}
(out/'release.json').write_text(json.dumps(record,indent=2)+'\n')
(out/'README.md').write_text('''# Printed system connections in scanned scores\n\nThe updated universal Mac app includes direct cropping in the part Preview: select a system and drag a blue edge; score, saving and export use the same edited band. That feature was already shipped and remains unchanged.\n\nThis release improves Find Similar Systems. It checks actual continuous original ink even when brackets cause detected staff starts to differ. All source-ink thresholds, missing-staff checks, complete-system checks, ambiguity handling, count requirements and explicit acceptance remain.\n\nOn the complete ten-page Hear My Prayer scan, two reviewed examples now produce26 correct further system proposals (19 source-supported,7 needing review), compared with none before. Six systems remain manual. Independent source review agreed on every proposed staff identity and roster. The existing32 challenge cases pass with exactly unchanged result semantics. This is an assistive improvement, not automatic instrument recognition or a duration counter.\n\nOnly ScoreSystemTemplateMatcher.swift differs from the preceding published source snapshot. The native crop analyzer and private crop candidates are unchanged/excluded. All45 inputs and35 Swift compile files were independently checked; both architectures target macOS14. Built and extracted bundles pass strict ad-hoc signature checks. This is not a notarized Developer ID release.\n\nPublication atomically replaced only the download ZIP, retaining its predecessor. The running app and user documents were not touched.\n''')
(out/'manifest.json').write_text(json.dumps({p.name:{'sha256':sha(p),'bytes':p.stat().st_size} for p in sorted(out.iterdir()) if p.is_file() and p.name!='manifest.json'},indent=2)+'\n')
print(json.dumps({'published':str(public),'sha256':sha(public),'bytes':public.stat().st_size},indent=2))
