from pathlib import Path
import json,hashlib,shutil,tarfile
w=Path('.build/brahms-residual-source-separation-2026-10-03');r=Path('Tests/quality_control/brahms-residual-source-separation-2026-10-03');r.mkdir(parents=True,exist_ok=True)
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.loads(p.read_text())
old=Path('Tests/quality_control/brahms-reviewed-cleanup-2026-10-03');delivery=Path('output/pdf/auto-qc-2026-10-03/brahms-quartet-93521-viola-in-tempo-repair');m=read(delivery/'manifest.json');native=Path('Partsmith/Core/Detection/NativeScorePageAnalyzer.swift');planner=Path('Partsmith/Core/Detection/ScoreExtractionPlanner.swift')
shutil.copy2(old/'immutable-thirteen-local-obligations.json',w/'immutable-thirteen-local-obligations.json')
ob={'status':'Frozen for future trials after independent original/current-corrected source inspection; no candidate or proposed-crop trial run in this study.','basis':'Seven earlier source-defined target envelopes adopted without edits after current-source visual review and exact4px/pt corrected raster equivalence. They are conservative envelopes, not pixel ownership masks.','coordinateSpace':'Current saved corrected top-down PDF points. Pages24/31 have no rectification; pages28/38 are corrected. Original sources also inspected separately, never mapped approximately.','currentOriginalSHA256':m['sourceSHA256'],'currentCorrectedSHA256':m['reviewSourceSHA256'],'priorObligationFileSHA256':sha(w/'frozen-source-obligations.json'),'tenGuardSHA256':sha(w/'immutable-ten-source-guards.json'),'thirteenLocalObligationsSHA256':sha(w/'immutable-thirteen-local-obligations.json'),'targetRegions':read(w/'frozen-source-obligations.json')['targetRegions'],'freshVisualEvidence':read(w/'source-context-index.json')+read(w/'source-detail-index.json'),'sourceJudgments':[
{'page':24,'finding':'Viola and Cello have separate musical phrases; surviving right-boundary connectivity is structural. Viola low cresc./forte/hairpins and Cello high closing half notes/sharp/slur occupy overlapping vertical bands. Both full neighboring cores can be excluded, but a single full-width rectangle cannot remove every foreign mark.'},
{'page':28,'finding':'The first internal barline connects the two violin rows. Adjacent violin noteheads, their own stems/flag and upper/lower slurs are distinct from that physical boundary. Full first and second violin cores can be separated; preserve ViolinII low flagged note/hairpin/forte and Viola high-note/slur remnants where ranges overlap.'},
{'page':31,'finding':'The right system boundary is visibly separate from the last ViolinI beam and ViolinII flagged notes, lower slur and crescendo. Local staff lines are damaged and curved; their missing fragments cannot be fabricated as full lines. Full ViolinI core can be excluded while retaining ViolinII source envelope.'},
{'page':38,'finding':'The accepted body location is on a Cello tie at a continuing measureline, not a separate notehead. All Cello noteheads/ties belong to Cello; the vertical measureline does not couple them to Viola. Viola final high note/double arc overlaps the vertical range of ViolinII lower markings; perfect neighbor-fragment removal is impossible with one horizontal rectangle.'}]}
(w/'source-obligations-before-future-trials.json').write_text(json.dumps(ob,indent=2)+'\n')
inputs={str(p):sha(p) for p in [delivery/'manifest.json',delivery/'original-detection-plan.json',delivery/m['project']/'project.json',delivery/m['project']/'source.pdf',delivery/m['reviewSourceFile'],Path('.build/brahms93521-full-production-workflow-draft-2026-10-03/recognized-inventory.json'),native,planner,Path('Tests/quality_control/p31-spine-provenance-2026-10-03/gate-summary.json'),Path('Tests/quality_control/terminal-body-continuation-2026-10-03/source-review.json'),old/'frozen-source-obligations.json']}
(w/'input-bindings.json').write_text(json.dumps({'files':inputs,'rectifications':m['rectifications'],'analyzer':'9f8d7ef80a27569ca3f5711388ad5876326a2931d60ecd77b2703d0aba235f01','noNativeRerun':True},indent=2)+'\n')
causes=[
{'pages':[24],'rows':['p24-s2-viola','p24-s2-cello'],'kind':'ordinary-shared-component','nativeRect':[285,1042,1643,1306],'owners':[6,7],'causalSource':'Right system boundary plus staff-line-connected local musical branches.','historicalGate':'Local geometry accepted; lower-core support49/57 below88% gate. Historical exact-source probe, not rerun.','prohibitedShortcut':'Dropping shared component loses both parts local notes. Wider core tolerance or more other complete cores does not distinguish attached musical stems.'},
{'pages':[28],'rows':['p28-s1-violin1','p28-s1-violin2'],'kind':'ordinary-shared-component','nativeRect':[132,69,969,229],'owners':[0,1],'causalSource':'Interior measureline near corrected x98pt; original staff-line fragments connect otherwise separate phrases.','historicalGate':'Local geometry accepted; upper-core support29/34 below88% gate. Historical exact-source probe, not rerun.','prohibitedShortcut':'Aligned multi-core barline fallback already loses four-core shared musical chord controls; retain exact attached branches and stop when ownership unresolved.'},
{'pages':[31],'rows':['p31-s1-violin2'],'kind':'ordinary-shared-structural-component','nativeRect':[1641,200,1651,350],'owners':[0,1],'causalSource':'448-pixel narrow leaning right boundary and short staff-line stubs; no musical head, beam, slur or dynamic in this component.','historicalGate':'Ordered-line trace fails final damaged window before connector proof; staff lines are visibly missing. A thin/slender filter is unsafe on steep slur/gliss controls.','prohibitedShortcut':'Bounding-box thinness, row width or proximity to page edge is not semantic ownership proof.'},
{'pages':[38],'rows':['p38-s1-viola','p38-s1-cello'],'kind':'outward-ownership-alternative','nativeRect':[135,244,971,394],'owners':[2,3],'causalSource':'Compact one-sided patch at Cello tie/continuing measureline; patch[411,374,414,376], spine[409,411).','historicalGate':'Terminal-body witness preserves musical interpretation; native lines640–663 append broad alternative; planner lines1121 onward expand every contacted owner. Current inventory explicitly marks this component isOwnershipAlternative=true.','prohibitedShortcut':'Do not turn a compact patch, curve crossing or even two local heads on a structural bar into shared cross-staff musical ownership. Blanket tie/branch rejection also cuts real tied notes.'}]
(w/'causal-findings.json').write_text(json.dumps({'sourceReview':True,'newCandidateTested':False,'cases':causes},indent=2)+'\n')
for p in sorted(w.rglob('*')):
 if p.is_file() and p.name!='freeze_review.py':
  dest=r/p.relative_to(w);dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dest)
shutil.copy2(w/'freeze_review.py',r/'freeze_review.py')
print('source obligations',sha(r/'source-obligations-before-future-trials.json'))
